(in-package :sb-vm)
(defknown fast-mpsc-queue:atomic-swap-car (cons t)
    t (always-translatable)
  :overwrite-fndb-silently t)
(define-vop (fast-mpsc-queue:atomic-swap-car)
  (:translate fast-mpsc-queue:atomic-swap-car)
  (:policy :fast-safe)
  (:args (cons :scs (descriptor-reg))
         (val :scs (descriptor-reg any-reg) :target r))
  (:temporary (:sc descriptor-reg) tmp)
  (:results (r :scs (descriptor-reg any-reg)))
  (:vop-var vop)
  (:generator
   5
   (emit-gengc-barrier cons nil tmp (vop-nth-arg 1 vop) val)
   (move r val)
   (inst xchg (ea (- list-pointer-lowtag) cons) r)))
